language: node_js

node_js:
# 13.5+ is broken, pin until https://github.com/nodejs/node/issues/31142 is resolved
  - 13.4.0
  - 12
  - 10

os:
  - linux

cache:
  directories:
    - $HOME/.npm

notifications:
  email: false
